llm_chain:
  platforms:
    openai:
      type: 'openai'
      api_key: '%env(OPENAI_API_KEY)%'
  llms:
    original_gpt:
      platform: 'openai'
  embeddings:
    original_embeddings:
      platform: 'openai'
