twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
      settings_handler: '@DZunke\NovDoc\Settings\Application\SettingsHandler'
      library_root: '@DZunke\NovDoc\Library\Domain\RootDirectory'
