parameters:
  router.request_context.scheme: 'https'
  asset.request_context.secure: true

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $openAIKey: '%env(string:OPENAI_API_KEY)%'
      string $dotEnvFile: '%kernel.project_dir%/.env'
      string $documentStoragePath: '%kernel.project_dir%/var/documents'
      string $directoryStoragePath: '%kernel.project_dir%/var/directories'
      string $vectorDocumentsPath: '%kernel.project_dir%/var/data/document'
      string $vectorImagesPath: '%kernel.project_dir%/var/data/image'
      string $lastConversationFilePath: '%kernel.project_dir%/var/conversations/last_conversation.json'
      string $settingsFilePath: '%kernel.project_dir%/var/settings.json'
      string $changelogFile: '%kernel.project_dir%/CHANGELOG.md'
      string $libraryImageStoragePath: '%kernel.project_dir%/var/library/images'

  DZunke\NovDoc\:
    resource: '../src/*'
    exclude: '../src/Web/{Model,Kernel.php}'

  DZunke\NovDoc\Web\Controller\:
    resource: '../src/Web/Controller'
    tags: [ 'controller.service_arguments' ]

  OskarStark\Twig\ReadableFilesizeExtension:
    tags: [ 'twig.extension' ]

  League\CommonMark\Extension\Table\TableExtension:
    tags: [ 'twig.markdown.league_extension' ]
