name: Build PHPDesktop Archive

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  phpdesktop:
    name: build phpdesktop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: do application build
        run: make phpdesktop

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          command: 'mv build/ NovDoc-PHPDesktop-${{ github.ref_name }}/'
          path: "NovDoc-PHPDesktop-${{ github.ref_name }}"
          filename: "NovDoc-PHPDesktop-${{ github.ref_name }}.zip"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: "NovDoc-PHPDesktop-${{ github.ref_name }}.zip"
